#!/usr/bin/env python3
"""Generate the APC error-code name table from eSPDI_def.h.

Reads every `#define APC_<NAME> <non-positive integer>` (the SDK's error-code
block) and emits switch cases mapping the value back to its define name, so
runtime errors can print `APC_NOT_SUPPORT_RES` instead of a bare `-27`.
Keeping the SDK header as the single source means an SDK upgrade regenerates
the table with no hand edits.

Usage: gen_apc_error_names.py <eSPDI_def.h> <output.inc>
"""
import re
import sys

DEFINE = re.compile(r"^\s*#define\s+(APC_\w+)\s+(-\d+|0)\s*(?://.*|/\*.*)?$")


def main() -> int:
    header, out_path = sys.argv[1], sys.argv[2]
    names = {}  # value -> first define seen (later duplicates are aliases)
    with open(header, encoding="utf-8", errors="replace") as f:
        for line in f:
            m = DEFINE.match(line)
            if not m:
                continue
            name, value = m.group(1), int(m.group(2))
            names.setdefault(value, name)
    if not names:
        sys.exit(f"no APC error defines found in {header}")
    with open(out_path, "w", encoding="utf-8") as out:
        out.write("// Generated by cmake/gen_apc_error_names.py from "
                  "eSPDI_def.h — do not edit.\n")
        for value in sorted(names, reverse=True):
            out.write(f'case {value}: return "{names[value]}";\n')
    return 0


if __name__ == "__main__":
    sys.exit(main())
